### ISSUE TITLE
word wrap

### ISSUE THREAD

**Issue by a-i-m-a-r** [jschildgen/reveal.js-poll-plugin#2]
When the possible answers are quite long, they are not properly displayed in small screens, e.g. smartphones.
The text overflows and it is not possible to read it.
I have created a style css file for the buttons and referred to it into index.php, with the usual:
`overflow-wrap: break-word;`
`word-wrap: break-word;`
`white-space: normal;`
but none is working.
How could I insert a line break and show a multiline text in the buttons of the mobile devices if they screen is too narrow?

**Comment by jschildgen** [comment]
Hi, I fixed this issue this morning. Adding white-space:normal; to the buttons was sufficient.

![image](https://user-images.githubusercontent.com/11808058/135073436-0938cdc3-4068-4d36-8650-bb80ffbba516.png)

Mind to reload the page on the device and empty the cache.

**Comment by a-i-m-a-r** [comment]
Great! Thank you. 
I reloaded the page, but did not emptied the cache. Thanks also for the hint.
