### ISSUE TITLE
Extending for question/answer

### ISSUE THREAD

**Issue by markNZed** [jschildgen/reveal.js-poll-plugin#3]
Hi, this is a cool feature for Reveal.js, thanks. I was looking to include a quiz and there is a Reveal.js plugin for quiz but it does not have the feature of collecting the results into a summary. If this Poll plugin could be extended to allow for a multiple choice question then it could largely replace what I'm doing. What might be the best way to go about realizing this?

**Comment by jschildgen** [comment]
I do not really understand what you mean. The poll shows a multiple-choise question. And the results of the poll (how many people chose which answer) is shown directly afterwards.

**Comment by markNZed** [comment]
Ah great- I was just assuming it was true/false - sorry! So it looks like it already does what I want.

**Comment by jschildgen** [comment]
You can have as many answers as you want:

![image](https://user-images.githubusercontent.com/11808058/224978937-143c62f1-c431-4021-adf4-54e158827f6f.png)

**Comment by markNZed** [comment]
I've been looking into so many different things around Reveal I am getting myself confused, sorry again!
